### PR TITLE
Add Anne as an editor. Move John to former editors list.

### PR DESCRIPTION
**Pull request by hober**
I'd also like @bvandersloot-mozilla's signoff.

***
<a href="https://pr-preview.s3.amazonaws.com/privacycg/storage-access/pull/119.html" title="Last updated on Sep 27, 2022, 6:29 PM UTC (896f75d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/privacycg/storage-access/119/d9d8f41...896f75d.html" title="Last updated on Sep 27, 2022, 6:29 PM UTC (896f75d)">Diff</a>

### CODE REVIEW

**Review by johannhof — APPROVED** [review]
🎉

**Review by erik-anderson — APPROVED** [review]

**Review by johnwilander — APPROVED** [review]
Thanks for offering to take this over the finish line together with the other co-editors, Anne! Appreciated.

Could one humbly request to be mentioned as the inventor (or such) of this in the Acknowledgments section? 😋

**Review by martinthomson — APPROVED** [review]
More Anne is always good.

**Comment by johannhof** [comment]
> Could one humbly request to be mentioned as the inventor (or such) of this in the Acknowledgments section? 😋

That seems appropriate to me, I can do it in a follow-up :)

**Review by annevk — APPROVED** [review]

**Pull request merged**
